export default {
	emojiList: [
		[
			{ url: 'angry-face.png', alt: '[angry face]' },
			{ url: 'anguished-face.png', alt: '[anguished face]' },
			{ url: 'anxious-face-with-sweat.png', alt: '[anxious face with sweat]' },
			{ url: 'astonished-face.png', alt: '[astonished face]' },
			{ url: 'beaming-face-with-smiling-eyes.png', alt: '[beaming face with smiling eyes]' },
			{ url: 'confounded-face.png', alt: '[confounded face]' },
			{ url: 'confused-face.png', alt: '[confused face]' },
			{ url: 'crying-face.png', alt: '[crying face]' },
			{ url: 'disappointed-face.png', alt: '[disappointed face]' },
			{ url: 'dizzy-face.png', alt: '[dizzy face]' },
			{ url: 'downcast-face-with-sweat.png', alt: '[downcast face with sweat]' },
			{ url: 'drooling-face.png', alt: '[drooling face]' },
			{ url: 'expressionless-face.png', alt: '[expressionless face]' },
			{ url: 'face-blowing-a-kiss.png', alt: '[face blowing a kiss]' },
			{ url: 'face-savoring-food.png', alt: '[face savoring food]' },
			{ url: 'face-screaming-in-fear.png', alt: '[face screaming in fear]' },
			{ url: 'face-vomiting.png', alt: '[face vomiting]' },
			{ url: 'face-with-hand-over-mouth.png', alt: '[face with hand over mouth]' },
			{ url: 'face-with-head-bandage.png', alt: '[face with head bandage]' },
			{ url: 'face-with-medical-mask.png', alt: '[face with medical mask]' },
			{ url: 'face-with-monocle.png', alt: '[face with monocle]' },
			{ url: 'face-with-open-mouth.png', alt: '[face with open mouth]' },
			{ url: 'face-with-raised-eyebrow.png', alt: '[face with raised eyebrow]' }
		],
		[
			{ url: 'face-with-rolling-eyes.png', alt: '[face with rolling eyes]' },
			{ url: 'face-with-steam-from-nose.png', alt: '[face with steam from nose]' },
			{ url: 'face-with-symbols-on-mouth.png', alt: '[face with symbols on mouth]' },
			{ url: 'face-with-tears-of-joy.png', alt: '[face with tears of joy]' },
			{ url: 'face-with-thermometer.png', alt: '[face with thermometer]' },
			{ url: 'face-with-tongue.png', alt: '[face with tongue]' },
			{ url: 'face-without-mouth.png', alt: '[face without mouth]' },
			{ url: 'flushed-face.png', alt: '[flushed face]' },
			{ url: 'frowning-face-with-open-mouth.png', alt: '[frowning face with open mouth]' },
			{ url: 'frowning-face.png', alt: '[frowning face]' },
			{ url: 'grimacing-face.png', alt: '[grimacing face]' },
			{ url: 'grinning-face-with-big-eyes.png', alt: '[grinning face with big eyes]' },
			{ url: 'grinning-face-with-smiling-eyes.png', alt: '[grinning face with smiling eyes]' },
			{ url: 'grinning-face-with-sweat.png', alt: '[grinning face with sweat]' },
			{ url: 'grinning-face.png', alt: '[grinning face]' },
			{ url: 'grinning-squinting-face.png', alt: '[grinning squinting face]' },
			{ url: 'hot-face.png', alt: '[hot face]' },
			{ url: 'hugging-face.png', alt: '[hugging face]' },
			{ url: 'hushed-face.png', alt: '[hushed face]' },
			{ url: 'kissing-face-with-closed-eyes.png', alt: '[kissing face with closed eyes]' },
			{ url: 'kissing-face-with-smiling-eyes.png', alt: '[kissing face with smiling eyes]' },
			{ url: 'kissing-face.png', alt: '[kissing face]' },
			{ url: 'loudly-crying-face.png', alt: '[loudly crying face]' }
		],
		[
			{ url: 'lying-face.png', alt: '[lying face]' },
			{ url: 'nauseated-face.png', alt: '[nauseated face]' },
			{ url: 'neutral-face.png', alt: '[neutral face]' },
			{ url: 'pensive-face.png', alt: '[pensive face]' },
			{ url: 'persevering-face.png', alt: '[persevering face]' },
			{ url: 'pleading-face.png', alt: '[pleading face]' },
			{ url: 'relieved-face.png', alt: '[relieved face]' },
			{ url: 'rolling-on-the-floor-laughing.png', alt: '[rolling on the floor laughing]' },
			{ url: 'sad-but-relieved-face.png', alt: '[sad but relieved face]' },
			{ url: 'shushing-face.png', alt: '[shushing face]' },
			{ url: 'sleeping-face.png', alt: '[sleeping face]' },
			{ url: 'sleepy-face.png', alt: '[sleepy face]' },
			{ url: 'slightly-frowning-face.png', alt: '[slightly frowning face]' },
			{ url: 'slightly-smiling-face.png', alt: '[slightly smiling face]' },
			{ url: 'smiling-face-with-halo.png', alt: '[smiling face with halo]' },
			{ url: 'smiling-face-with-heart-eyes.png', alt: '[smiling face with heart eyes]' },
			{ url: 'smiling-face-with-hearts.png', alt: '[smiling face with hearts]' },
			{ url: 'smiling-face-with-smiling-eyes.png', alt: '[smiling face with smiling eyes]' },
			{ url: 'smiling-face-with-sunglasses.png', alt: '[smiling face with sunglasses]' },
			{ url: 'smiling-face.png', alt: '[smiling face]' },
			{ url: 'smirking-face.png', alt: '[smirking face]' },
			{ url: 'sneezing-face.png', alt: '[sneezing face]' },
			{ url: 'squinting-face-with-tongue.png', alt: '[squinting face with tongue]' }
		],
		[
			{ url: 'star-struck.png', alt: '[star struck]' },
			{ url: 'thinking-face.png', alt: '[thinking face]' },
			{ url: 'tired-face.png', alt: '[tired face]' },
			{ url: 'unamused-face.png', alt: '[unamused face]' },
			{ url: 'upside-down-face.png', alt: '[upside down face]' },
			{ url: 'weary-face.png', alt: '[weary face]' },
			{ url: 'winking-face-with-tongue.png', alt: '[winking face with tongue]' },
			{ url: 'winking-face.png', alt: '[winking face]' },
			{ url: 'woozy-face.png', alt: '[woozy face]' },
			{ url: 'worried-face.png', alt: '[worried face]' },
			{ url: 'yawning-face.png', alt: '[yawning face]' },
			{ url: 'zany-face.png', alt: '[zany face]' },
			{ url: 'zipper-mouth-face.png', alt: '[zipper mouth face]' }
		]
		
	],
	//表情图片图床名称 ，由于我上传的第三方图床名称会有改变，所以有此数据来做对应，您实际应用中应该不需要
	//2020.1.16. 如果是发布微信小程序,这些emoji图标会占用空间,可以考虑线上的,具体转换在pages/chat/chat.vue  中的 replaceEmoji 函数
	onlineEmoji: {
		'100.gif': '100.gif',
		'101.gif': 'AbN3ut.gif',
		'102.gif': 'AbNM3d.gif',
		'103.gif': 'AbN8DP.gif',
		'104.gif': 'AbNljI.gif',
		'105.gif': 'AbNtUS.gif',
		'106.gif': 'AbNGHf.gif',
		'107.gif': 'AbNYE8.gif',
		'108.gif': 'AbNaCQ.gif',
		'109.gif': 'AbNN4g.gif',
		'110.gif': 'AbN0vn.gif',
		'111.gif': 'AbNd3j.gif',
		'112.gif': 'AbNsbV.gif',
		'113.gif': 'AbNwgs.gif',
		'114.gif': 'AbNrD0.gif',
		'115.gif': 'AbNDuq.gif',
		'116.gif': 'AbNg5F.gif',
		'117.gif': 'AbN6ET.gif',
		'118.gif': 'AbNcUU.gif',
		'119.gif': 'AbNRC4.gif',
		'120.gif': 'AbNhvR.gif',
		'121.gif': 'AbNf29.gif',
		'122.gif': 'AbNW8J.gif',
		'123.gif': 'AbNob6.gif',
		'124.gif': 'AbN5K1.gif',
		'125.gif': 'AbNHUO.gif',
		'126.gif': 'AbNIDx.gif',
		'127.gif': 'AbN7VK.gif',
		'128.gif': 'AbNb5D.gif',
		'129.gif': 'AbNX2d.gif',
		'130.gif': 'AbNLPe.gif',
		'131.gif': 'AbNjxA.gif',
		'132.gif': 'AbNO8H.gif',
		'133.gif': 'AbNxKI.gif',
		'134.gif': 'AbNzrt.gif',
		'135.gif': 'AbU9Vf.gif',
		'136.gif': 'AbUSqP.gif',
		'137.gif': 'AbUCa8.gif',
		'138.gif': 'AbUkGQ.gif',
		'139.gif': 'AbUFPg.gif',
		'140.gif': 'AbUPIS.gif',
		'141.gif': 'AbUZMn.gif',
		'142.gif': 'AbUExs.gif',
		'143.gif': 'AbUA2j.gif',
		'144.gif': 'AbUMIU.gif',
		'145.gif': 'AbUerq.gif',
		'146.gif': 'AbUKaT.gif',
		'147.gif': 'AbUmq0.gif',
		'148.gif': 'AbUuZV.gif',
		'149.gif': 'AbUliF.gif',
		'150.gif': 'AbU1G4.gif',
		'151.gif': 'AbU8z9.gif',
		'152.gif': 'AbU3RJ.gif',
		'153.gif': 'AbUYs1.gif',
		'154.gif': 'AbUJMR.gif',
		'155.gif': 'AbUadK.gif',
		'156.gif': 'AbUtqx.gif',
		'157.gif': 'AbUUZ6.gif',
		'158.gif': 'AbUBJe.gif',
		'159.gif': 'AbUdIO.gif',
		'160.gif': 'AbU0iD.gif',
		'161.gif': 'AbUrzd.gif',
		'162.gif': 'AbUDRH.gif',
		'163.gif': 'AbUyQA.gif',
		'164.gif': 'AbUWo8.gif',
		'165.gif': 'AbU6sI.gif',
		'166.gif': 'AbU2eP.gif',
		'167.gif': 'AbUcLt.gif',
		'168.gif': 'AbU4Jg.gif',
		'169.gif': 'AbURdf.gif',
		'170.gif': 'AbUhFS.gif',
		'171.gif': 'AbU5WQ.gif',
		'172.gif': 'AbULwV.gif',
		'173.gif': 'AbUIzj.gif',
		'174.gif': 'AbUTQs.gif',
		'175.gif': 'AbU7yn.gif',
		'176.gif': 'AbUqe0.gif',
		'177.gif': 'AbUHLq.gif',
		'178.gif': 'AbUOoT.gif',
		'179.gif': 'AbUvYF.gif',
		'180.gif': 'AbUjFU.gif',
		'181.gif': 'AbaSSJ.gif',
		'182.gif': 'AbUxW4.gif',
		'183.gif': 'AbaCO1.gif',
		'184.gif': 'Abapl9.gif',
		'185.gif': 'Aba9yR.gif',
		'186.gif': 'AbaFw6.gif',
		'187.gif': 'Abaiex.gif',
		'188.gif': 'AbakTK.gif',
		'189.gif': 'AbaZfe.png',
		'190.gif': 'AbaEFO.gif',
		'191.gif': 'AbaVYD.gif',
		'192.gif': 'AbamSH.gif',
		'193.gif': 'AbaKOI.gif',
		'194.gif': 'Abanld.gif',
		'195.gif': 'Abau6A.gif',
		'196.gif': 'AbaQmt.gif',
		'197.gif': 'Abal0P.gif',
		'198.gif': 'AbatpQ.gif',
		'199.gif': 'Aba1Tf.gif',
		'200.png': 'Aba8k8.png',
		'201.png': 'AbaGtS.png',
		'202.png': 'AbaJfg.png',
		'203.png': 'AbaNlj.png',
		'204.png': 'Abawmq.png',
		'205.png': 'AbaU6s.png',
		'206.png': 'AbaaXn.png',
		'207.png': 'Aba000.png',
		'208.png': 'AbarkT.png',
		'209.png': 'AbastU.png',
		'210.png': 'AbaB7V.png',
		'211.png': 'Abafn1.png',
		'212.png': 'Abacp4.png',
		'213.png': 'AbayhF.png',
		'214.png': 'Abag1J.png',
		'215.png': 'Aba2c9.png',
		'216.png': 'AbaRXR.png',
		'217.png': 'Aba476.png',
		'218.png': 'Abah0x.png',
		'219.png': 'Abdg58.png'
	}
	
};